// Generated by CoffeeScript 1.4.0

dataService.factory('nearestShelters', [
  '$resource', function($resource) {
    return function(params) {
      return $resource('http://api.huaxianweiyi.com:9000', {
        callback: 'JSON_CALLBACK'
      }, {
        query_jsonp: {
          method: 'JSONP',
          params: {
            longitude: params.longitude,
            latitude: params.latitude
          }
        }
      });
    };
  }
]);
